#!/usr/bin/env python3
"""
Add structured thinking traces to existing apisynth training records.

Reads data/<vendor>/*/training.jsonl records and writes them back with a
"thinking" field inserted between "question" and "api_call". The trace is
derived deterministically from the api_call — no teacher LLM required for
simple single-endpoint records.

For complex multi-step records (future PoC workflows), the thinking field
should be generated by a teacher LLM and passed in as an override file.

Vendor-specific knowledge (synonyms, domain notes, manual traces) is loaded
from apis/<vendor>/thinking_knowledge.yaml when --vendor-dir is provided.
See apis/example/thinking_knowledge.yaml for the format.

Usage:
    # Enrich all endpoints (generic traces, no vendor knowledge):
    python scripts/add_thinking.py --input-dir data/<vendor>

    # Enrich with vendor-specific domain knowledge:
    python scripts/add_thinking.py --input-dir data/<vendor> --vendor-dir apis/<vendor>

    # Force re-generate thinking for records that already have it:
    python scripts/add_thinking.py --input-dir data/<vendor> --vendor-dir apis/<vendor> --force

    # Dry-run: print sample thinking traces without writing:
    python scripts/add_thinking.py --input-dir data/<vendor> --dry-run --sample 5

    # Enrich a single endpoint:
    python scripts/add_thinking.py --input-dir data/<vendor> --endpoint programs
"""

import argparse
import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Synonym detection and domain-specific knowledge
#
# These dicts are populated at runtime by load_vendor_knowledge().
# Vendor-specific data lives in apis/<vendor>/thinking_knowledge.yaml (gitignored).
# See apis/example/thinking_knowledge.yaml for the format.
# ---------------------------------------------------------------------------

_ENTITY_SYNONYMS: dict[str, list[str]] = {}
_SYNONYM_DOMAIN_NOTES: dict[tuple[str, str], str] = {}
_NO_FILTER_PHRASES: list[str] = [
    "my ", "show me my ", "show my ", "list my ", "get my ",
    "what are my ", "what's my ", "give me my ",
]
_MEASUREMENT_DESCRIPTOR_PHRASES: list[str] = []


def load_vendor_knowledge(vendor_dir) -> None:
    """Load vendor-specific synonym/domain knowledge from <vendor_dir>/thinking_knowledge.yaml.

    Populates the module-level _ENTITY_SYNONYMS, _SYNONYM_DOMAIN_NOTES, _MANUAL,
    _MANUAL_QOC, _NO_FILTER_PHRASES, and _MEASUREMENT_DESCRIPTOR_PHRASES dicts.
    Safe to call multiple times; each call replaces the previous vendor's data.
    Does nothing if the file doesn't exist.
    """
    global _ENTITY_SYNONYMS, _SYNONYM_DOMAIN_NOTES, _NO_FILTER_PHRASES
    global _MEASUREMENT_DESCRIPTOR_PHRASES, _MANUAL, _MANUAL_QOC

    path = Path(vendor_dir).expanduser() / "thinking_knowledge.yaml"
    if not path.exists():
        return

    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML required for vendor knowledge: pip install pyyaml")

    with open(path) as f:
        data = yaml.safe_load(f) or {}

    _ENTITY_SYNONYMS = data.get("entity_synonyms") or {}
    # Convert nested {entity: {synonym: note}} → tuple-keyed dict
    raw_notes = data.get("domain_notes") or {}
    _SYNONYM_DOMAIN_NOTES = {
        (syn, entity): note
        for entity, syns in raw_notes.items()
        for syn, note in syns.items()
    }
    if data.get("no_filter_phrases"):
        _NO_FILTER_PHRASES = data["no_filter_phrases"]
    if data.get("measurement_descriptor_phrases"):
        _MEASUREMENT_DESCRIPTOR_PHRASES = data["measurement_descriptor_phrases"]
    if data.get("manual_traces"):
        _MANUAL.update(data["manual_traces"])
    if data.get("manual_traces_qoc"):
        _MANUAL_QOC.update(data["manual_traces_qoc"])

def _detect_synonym(question: str, entity: str) -> str | None:
    """Return the synonym word found in question for entity, or None."""
    q = question.lower()
    for syn in _ENTITY_SYNONYMS.get(entity, []):
        if syn in q:
            return syn
    return None

def _possession_no_filter(question: str) -> bool:
    """Return True if question uses possessive phrasing that implies no filter."""
    q = question.lower()
    return any(q.startswith(p) or f" {p}" in q for p in _NO_FILTER_PHRASES)

def _measurement_descriptor(question: str) -> bool:
    """Return True if question uses a phrase that describes measurement type, not a filter."""
    q = question.lower()
    return any(p in q for p in _MEASUREMENT_DESCRIPTOR_PHRASES)


# ---------------------------------------------------------------------------
# Entity and operation inference from endpoint strings
# ---------------------------------------------------------------------------

_EP_ENTITY = [
    (r"/content/programs/\{",        "program",      True),
    (r"/content/programs$",          "programs",     False),
    (r"/content/episodes/\{",        "episode",      True),
    (r"/content/episodes$",          "episodes",     False),
    (r"/content/networks/\{",        "network",      True),
    (r"/content/networks$",          "networks",     False),
    (r"/content/media-groups$",      "media groups", False),
    (r"/content/metric-type",        "metric types", False),
    (r"/content/metrics/\{",         "content metric", True),
    (r"/measurements/\{",            "measurement",  True),
    (r"/measurements$",              "measurements", False),
    (r"/audiences/status$",          "audience statuses", False),
    (r"/audiences/\{[^}]+\}/exports",  "audience exports", False),
    (r"/audiences/\{",               "audience",     True),
    (r"/audiences$",                 "audiences",    False),
    (r"/currency-of-record",         "currency of record", False),
    (r"/consents$",                  "consents",     False),
    (r"/v1/me$",                     "me",           False),
]

def _infer(endpoint: str):
    """Return (entity_name, is_by_id) for an endpoint string."""
    for pattern, name, by_id in _EP_ENTITY:
        if re.search(pattern, endpoint):
            return name, by_id
    # Fallback: extract last path segment
    parts = endpoint.rstrip("/").split("/")
    last = parts[-1] if parts else "resource"
    is_by_id = last.startswith("{")
    if is_by_id:
        entity = parts[-2] if len(parts) > 1 else "resource"
    else:
        entity = last.replace("-", " ")
    return entity, is_by_id


# ---------------------------------------------------------------------------
# Thinking trace generators
# ---------------------------------------------------------------------------

def _thinking_me(question: str, params: dict) -> str:
    return (
        "Entity: current user (me)\n"
        "Operation: get my own profile — no ID needed\n"
        "Endpoint: GET /v1/me\n"
        "Params: {}"
    )


def _thinking_by_id(question: str, entity: str, endpoint: str, params: dict) -> str:
    list_endpoint = re.sub(r"/\{[^}]+\}$", "", endpoint)
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""

    lines = [f"Entity: {entity}"]
    if domain_note:
        lines.append(f"Domain: {domain_note}")
    elif synonym:
        lines.append(f"Synonym: '{synonym}' maps to {entity}")

    if not params:
        lines += [
            "Scope: single item lookup -- ID should be in params",
            f"Use:    {endpoint}",
            f"NOT:    {list_endpoint} (that is the list endpoint)",
        ]
        return "\n".join(lines)

    id_key, id_val = next(iter(params.items()))
    lines += [
        f"Scope: single item -- the prompt contains an explicit ID ({id_val})",
        f"The number {id_val} is the {id_key}, not a page number or filter",
        f"Use:    {endpoint}",
        f"NOT:    {list_endpoint} (that is the list endpoint, requires an ID)",
        f"Params: {json.dumps(params)}",
    ]
    return "\n".join(lines)


def _thinking_list(question: str, entity: str, endpoint: str, params: dict) -> str:
    id_endpoint = endpoint.rstrip("/") + "/{id}"
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""
    is_possession = _possession_no_filter(question)
    is_descriptor = _measurement_descriptor(question)

    lines = [f"Entity: {entity}"]
    if domain_note:
        lines.append(f"Domain: {domain_note}")
    elif synonym:
        lines.append(f"Synonym: '{synonym}' maps to {entity}")

    if not params:
        lines.append("Scope: list all -- no ID present, return the full list")
        if is_possession:
            lines.append(
                f"Possession note: '{question}' uses possessive phrasing but does NOT imply a filter. "
                f"{endpoint} already returns only the authenticated user's data."
            )
        if is_descriptor and entity == "measurements":
            lines.append(
                "No filter: descriptive phrases like 'reach and frequency' or 'campaign performance' "
                "describe the kind of data, not a query parameter. Do not add metric=, type=, or any filter."
            )
        lines += [
            f"Use:    {endpoint}",
            f"NOT:    {id_endpoint} (that requires an explicit numeric ID)",
            "Params: {}",
        ]
    else:
        page_size = params.get("pageSize")
        filters = {k: v for k, v in params.items() if k not in ("pageSize", "pageToken")}
        lines.append("Scope: list")
        if page_size:
            lines.append(f"Requested count: {page_size}")
        if filters:
            lines.append(f"Filters: {', '.join(f'{k}={v}' for k, v in filters.items())}")
        lines += [f"Endpoint: {endpoint}", f"Params: {json.dumps(params)}"]

    return "\n".join(lines)


def _thinking_chained(question: str, steps: list) -> str:
    if len(steps) < 2:
        return "Multi-step operation — see steps for details"

    step0 = steps[0]
    step1 = steps[1]
    entity0, _ = _infer(step0["endpoint"])
    entity1, _ = _infer(step1["endpoint"])

    # Find the template variable reference (e.g. {{steps.0.programId}})
    dep = ""
    for v in step1["params"].values():
        m = re.search(r"\{\{steps\.0\.(\w+)\}\}", str(v))
        if m:
            dep = m.group(1)
            break

    lines = [
        f"Goal: retrieve a specific {entity1} without a known ID",
        f"Step 0: list {entity0} to obtain an ID → {step0['endpoint']}",
        f"Step 1: use {{{{steps.0.{dep}}}}} to fetch the specific {entity1} → {step1['endpoint']}",
        "Two-step chain: the ID is resolved at runtime from step 0's response",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main dispatcher
# ---------------------------------------------------------------------------

# Manual traces are loaded from apis/<vendor>/thinking_knowledge.yaml

_MANUAL: dict[str, str] = {}  # populated by load_vendor_knowledge()



# ---------------------------------------------------------------------------
# QOC thinking trace generators (Question / Option / Criteria)
# For larger models and structured decision-matrix reasoning.
# ---------------------------------------------------------------------------

def _qoc_me(question: str, params: dict) -> str:
    return (
        "Question: Which endpoint returns the authenticated user's profile?\n"
        "Option:   GET /v1/me\n"
        "Criteria: No ID required. This endpoint always returns the current user. No alternatives.\n"
        "Params: {}"
    )


def _qoc_by_id(question: str, entity: str, endpoint: str, params: dict) -> str:
    list_endpoint = re.sub(r"/\{[^}]+\}$", "", endpoint)
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""

    lines = [f"Question: Retrieve a single {entity} by ID, or list all {entity}?"]
    if domain_note:
        lines.append(f"Domain:   {domain_note}")

    if not params:
        lines += [
            f"Option A: {endpoint}  (single item by ID)",
            f"Option B: {list_endpoint}  (list endpoint — no ID)",
            "Criteria: ID required for Option A but not provided. Defaulting to single-item intent.",
            f"Use:      {endpoint}",
        ]
        return "\n".join(lines)

    id_key, id_val = next(iter(params.items()))
    lines += [
        f"Option A: {endpoint}  (single item — requires {id_key})",
        f"Option B: {list_endpoint}  (list — no ID needed)",
        f"Criteria: Prompt contains explicit numeric ID '{id_val}'. "
        f"'{id_val}' is the {id_key}, not a page number or filter. Option A wins.",
        f"Params:   {json.dumps(params)}",
    ]
    return "\n".join(lines)


def _qoc_list(question: str, entity: str, endpoint: str, params: dict) -> str:
    id_endpoint = endpoint.rstrip("/") + "/{id}"
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""
    is_possession = _possession_no_filter(question)
    is_descriptor = _measurement_descriptor(question)

    lines = [f"Question: List all {entity}, or retrieve a single {entity} by ID?"]
    if domain_note:
        lines.append(f"Domain:   {domain_note}")

    if not params:
        lines += [
            f"Option A: {endpoint}  (list — no ID required)",
            f"Option B: {id_endpoint}  (single item — requires explicit numeric ID)",
        ]
        criteria = "No numeric ID in prompt."
        if is_possession:
            criteria += (
                f" Possessive phrasing does not imply an ID — "
                f"{endpoint} already scopes to the authenticated user."
            )
        if is_descriptor and entity == "measurements":
            criteria += (
                " Descriptive phrase does not translate to a filter parameter. "
                "Do not add metric=, type=, currencyOfRecord=, or any inferred filter."
            )
        criteria += " Option A wins."
        lines += [f"Criteria: {criteria}", "Params:   {}"]
    else:
        page_size = params.get("pageSize")
        filters = {k: v for k, v in params.items() if k not in ("pageSize", "pageToken")}
        lines += [
            f"Option A: {endpoint}  (list)",
            f"Option B: {id_endpoint}  (single item — no ID in prompt)",
            "Criteria: No ID present; list intent confirmed."
            + (f" Count: {page_size}." if page_size else "")
            + (f" Filters: {', '.join(f'{k}={v}' for k,v in filters.items())}." if filters else ""),
            f"Endpoint: {endpoint}",
            f"Params:   {json.dumps(params)}",
        ]
    return "\n".join(lines)


def _qoc_chained(question: str, steps: list) -> str:
    if len(steps) < 2:
        return "Multi-step operation — see steps for details"
    step0, step1 = steps[0], steps[1]
    entity0, _ = _infer(step0["endpoint"])
    entity1, _ = _infer(step1["endpoint"])
    dep = ""
    for v in step1["params"].values():
        m = re.search(r"\{\{steps\.0\.(\w+)\}\}", str(v))
        if m:
            dep = m.group(1)
            break
    return (
        f"Question: How to retrieve a specific {entity1} when only the name/context is known, not the ID?\n"
        f"Option A: Direct GET {step1['endpoint']} — requires known {dep}\n"
        f"Option B: Two-step — list {entity0} first, resolve ID, then fetch {entity1}\n"
        f"Criteria: ID not supplied in prompt. Option B required.\n"
        f"Step 0:   {step0['endpoint']} — obtain {dep}\n"
        f"Step 1:   {step1['endpoint']} — use {{{{steps.0.{dep}}}}}"
    )


# QOC manual overrides for the hard synonym/disambiguation cases
_MANUAL_QOC: dict[str, str] = {}  # populated by load_vendor_knowledge()


def generate_thinking(question: str, api_call: dict, style: str = "linear") -> str:
    """Return a thinking trace string for a training record.
    style: 'linear' (default, Entity/Scope/Use/NOT) or 'qoc' (Question/Option/Criteria).
    """
    normalized = question.strip().lower()

    if style == "qoc":
        if normalized in _MANUAL_QOC:
            return _MANUAL_QOC[normalized]
        if "steps" in api_call:
            return _qoc_chained(question, api_call["steps"])
        endpoint = api_call.get("endpoint", "")
        params = api_call.get("params", {})
        if re.search(r"/v1/me$", endpoint):
            return _qoc_me(question, params)
        entity, is_by_id = _infer(endpoint)
        return _qoc_by_id(question, entity, endpoint, params) if is_by_id else _qoc_list(question, entity, endpoint, params)

    # --- linear (default) ---
    if normalized in _MANUAL:
        return _MANUAL[normalized]

    if "steps" in api_call:
        return _thinking_chained(question, api_call["steps"])

    endpoint = api_call.get("endpoint", "")
    params = api_call.get("params", {})

    # /v1/me special case
    if re.search(r"/v1/me$", endpoint):
        return _thinking_me(question, params)

    entity, is_by_id = _infer(endpoint)
    if is_by_id:
        return _thinking_by_id(question, entity, endpoint, params)
    else:
        return _thinking_list(question, entity, endpoint, params)


# ---------------------------------------------------------------------------
# File processing
# ---------------------------------------------------------------------------

def enrich_file(path: Path, dry_run: bool = False, sample: int = 0, force: bool = False, style: str = "linear") -> int:
    """Read, enrich, and rewrite a training.jsonl file. Returns record count."""
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                print(f"  WARNING: skipping malformed JSON line in {path.name}")
                continue
            if force or "thinking" not in rec:
                try:
                    rec["thinking"] = generate_thinking(
                        rec["question"], rec["api_call"], style=style
                    )
                except KeyError as e:
                    print(f"  WARNING: skipping record missing key {e} in {path.name}")
                    continue
            records.append(rec)

    if sample > 0:
        for rec in records[:sample]:
            print(f"\nQ: {rec['question']!r}")
            print(f"Thinking:\n{rec['thinking']}")
            print(f"Answer: {json.dumps(rec['api_call'])[:80]}")
        return len(records)

    if not dry_run:
        with open(path, "w") as f:
            for rec in records:
                f.write(json.dumps(rec) + "\n")

    return len(records)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input-dir", required=True,
                        help="Directory containing endpoint subdirs with training.jsonl")
    parser.add_argument("--endpoint", default=None,
                        help="Process only this endpoint subdirectory")
    parser.add_argument("--trace-style", choices=["linear", "qoc"], default="linear",
                        help="Thinking trace format: 'linear' (Entity/Scope/Use) or 'qoc' (Question/Option/Criteria)")
    parser.add_argument("--force", action="store_true",
                        help="Re-generate thinking for records that already have it")
    parser.add_argument("--dry-run", action="store_true",
                        help="Do not write files — print counts only")
    parser.add_argument("--sample", type=int, default=0,
                        help="Print N sample thinking traces instead of writing")
    parser.add_argument("--vendor-dir", default=None,
                        help="Path to vendor directory (e.g. apis/acme) containing "
                             "thinking_knowledge.yaml. If omitted, generic traces are generated.")
    args = parser.parse_args()

    if args.vendor_dir:
        load_vendor_knowledge(args.vendor_dir)

    input_dir = Path(args.input_dir).expanduser()
    if not input_dir.is_dir():
        sys.exit(f"Not a directory: {input_dir}")

    if args.endpoint:
        files = [input_dir / args.endpoint / "training.jsonl"]
    else:
        files = sorted(input_dir.glob("*/training.jsonl"))

    if not files:
        sys.exit(f"No training.jsonl files found under {input_dir}")

    total = 0
    for path in files:
        if not path.exists():
            print(f"  SKIP  {path} (not found)")
            continue
        count = enrich_file(path, dry_run=args.dry_run, sample=args.sample, force=args.force, style=args.trace_style)
        action = "would write" if args.dry_run else "wrote"
        print(f"  {action}  {count:4d} records  {path.parent.name}")
        total += count

    print(f"\n  Total: {total} records across {len(files)} endpoint(s)")
    if args.dry_run:
        print("  (dry run — no files modified)")


if __name__ == "__main__":
    main()
