#!/usr/bin/env python3
"""
Add structured thinking traces to existing apisynth training records.

Reads data/videoamp/*/training.jsonl records and writes them back with a
"thinking" field inserted between "question" and "api_call". The trace is
derived deterministically from the api_call — no teacher LLM required for
simple single-endpoint records.

For complex multi-step records (future PoC workflows), the thinking field
should be generated by a teacher LLM and passed in as an override file.

Usage:
    # Enrich all endpoints in-place (adds "thinking" to existing records):
    python scripts/add_thinking.py --input-dir data/videoamp

    # Force re-generate thinking for records that already have it:
    python scripts/add_thinking.py --input-dir data/videoamp --force

    # Dry-run: print sample thinking traces without writing:
    python scripts/add_thinking.py --input-dir data/videoamp --dry-run --sample 5

    # Enrich a single endpoint:
    python scripts/add_thinking.py --input-dir data/videoamp --endpoint programs
"""

import argparse
import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Synonym detection and domain-specific knowledge
# ---------------------------------------------------------------------------

_ENTITY_SYNONYMS: dict[str, list[str]] = {
    "measurements": [
        "campaign", "campaigns", "report", "reports", "ad report", "ad reports",
        "analytics", "ad analytics", "impressions", "reach", "frequency",
        "performance", "campaign performance", "media metrics",
    ],
    "measurement": ["campaign", "report", "ad report"],
    "programs":    ["show", "shows", "series", "tv show", "tv shows"],
    "program":     ["show", "series", "tv show"],
    "networks":    ["channel", "channels", "tv channel", "tv channels", "broadcaster"],
    "network":     ["channel", "tv channel"],
    "audiences":   [
        "segment", "segments", "demographic", "demographics",
        "targeting segment", "targeting segments", "audience segment", "audience segments",
    ],
    "audience":    ["segment"],
}

# Domain-specific explanations for why synonym X maps to entity Y.
# Key: (synonym_word, canonical_entity)
_SYNONYM_DOMAIN_NOTES: dict[tuple[str, str], str] = {
    ("campaign",    "measurements"): "VideoAmp has no /campaigns endpoint. Ad campaign performance data is tracked as 'ad measurements' at /external/v1/measurements.",
    ("campaigns",   "measurements"): "VideoAmp has no /campaigns endpoint. Ad campaign data lives at /external/v1/measurements.",
    ("report",      "measurements"): "VideoAmp has no /reports endpoint. What users call 'reports' are 'measurements' in this API.",
    ("reports",     "measurements"): "VideoAmp has no /reports endpoint. Measurement results are at /external/v1/measurements.",
    ("analytics",   "measurements"): "VideoAmp has no /analytics endpoint. Analytics data is surfaced through the measurements endpoint.",
    ("impressions", "measurements"): "Impression data is a metric within VideoAmp measurements, not a separate endpoint.",
    ("reach",       "measurements"): "Reach and frequency are metrics within ad measurements, not filter parameters or a separate endpoint.",
    ("frequency",   "measurements"): "Reach and frequency are metrics within ad measurements, not filter parameters or a separate endpoint.",
    ("performance", "measurements"): "Campaign performance data lives at /external/v1/measurements, not a /performance endpoint.",
    ("channel",     "networks"):     "VideoAmp has no /channels endpoint. TV channels (broadcast networks) are 'networks' in this API at /external/v1/content/networks.",
    ("channels",    "networks"):     "VideoAmp has no /channels endpoint. TV channels are represented as networks.",
    ("channel",     "network"):      "VideoAmp has no /channels/{id} endpoint. TV channels are networks at /external/v1/content/networks/{id}.",
    ("segment",     "audiences"):    "VideoAmp has no /segments endpoint. Audience segments are 'audiences' in this API at /v1/audiences.",
    ("segments",    "audiences"):    "VideoAmp has no /segments endpoint. Targeting segments are audiences.",
    ("segment",     "audience"):     "VideoAmp has no /segments/{id} endpoint. Audience segments are at /v1/audiences/{id}.",
    ("demographic", "audiences"):    "VideoAmp has no /demographics endpoint. Demographic segments are audiences at /v1/audiences.",
    ("show",        "programs"):     "'Shows' in VideoAmp are 'programs' at /external/v1/content/programs.",
    ("shows",       "programs"):     "'Shows' in VideoAmp are 'programs' at /external/v1/content/programs.",
    ("series",      "programs"):     "'Series' are TV programs at /external/v1/content/programs in VideoAmp.",
    ("show",        "program"):      "'TV show' maps to a VideoAmp program at /external/v1/content/programs/{programId}.",
    ("series",      "program"):      "'Series' maps to a VideoAmp program at /external/v1/content/programs/{programId}.",
}

# Possession/adjective phrases that should NOT be treated as filters.
_NO_FILTER_PHRASES = [
    "my ", "show me my ", "show my ", "list my ", "get my ",
    "what are my ", "what's my ", "give me my ",
]

# Phrases that describe measurement types (not filter values).
_MEASUREMENT_DESCRIPTOR_PHRASES = [
    "reach and frequency", "reach & frequency", "ad analytics",
    "campaign performance", "media metrics", "media performance",
    "advertising analytics", "ad performance",
]

def _detect_synonym(question: str, entity: str) -> str | None:
    """Return the synonym word found in question for entity, or None."""
    q = question.lower()
    for syn in _ENTITY_SYNONYMS.get(entity, []):
        if syn in q:
            return syn
    return None

def _possession_no_filter(question: str) -> bool:
    """Return True if question uses possessive phrasing that implies no filter."""
    q = question.lower()
    return any(q.startswith(p) or f" {p}" in q for p in _NO_FILTER_PHRASES)

def _measurement_descriptor(question: str) -> bool:
    """Return True if question uses a phrase that describes measurement type, not a filter."""
    q = question.lower()
    return any(p in q for p in _MEASUREMENT_DESCRIPTOR_PHRASES)


# ---------------------------------------------------------------------------
# Entity and operation inference from endpoint strings
# ---------------------------------------------------------------------------

_EP_ENTITY = [
    (r"/content/programs/\{",        "program",      True),
    (r"/content/programs$",          "programs",     False),
    (r"/content/episodes/\{",        "episode",      True),
    (r"/content/episodes$",          "episodes",     False),
    (r"/content/networks/\{",        "network",      True),
    (r"/content/networks$",          "networks",     False),
    (r"/content/media-groups$",      "media groups", False),
    (r"/content/metric-type",        "metric types", False),
    (r"/content/metrics/\{",         "content metric", True),
    (r"/measurements/\{",            "measurement",  True),
    (r"/measurements$",              "measurements", False),
    (r"/audiences/status$",          "audience statuses", False),
    (r"/audiences/\{[^}]+\}/exports",  "audience exports", False),
    (r"/audiences/\{",               "audience",     True),
    (r"/audiences$",                 "audiences",    False),
    (r"/currency-of-record",         "currency of record", False),
    (r"/consents$",                  "consents",     False),
    (r"/v1/me$",                     "me",           False),
]

def _infer(endpoint: str):
    """Return (entity_name, is_by_id) for an endpoint string."""
    for pattern, name, by_id in _EP_ENTITY:
        if re.search(pattern, endpoint):
            return name, by_id
    # Fallback: extract last path segment
    parts = endpoint.rstrip("/").split("/")
    last = parts[-1] if parts else "resource"
    is_by_id = last.startswith("{")
    if is_by_id:
        entity = parts[-2] if len(parts) > 1 else "resource"
    else:
        entity = last.replace("-", " ")
    return entity, is_by_id


# ---------------------------------------------------------------------------
# Thinking trace generators
# ---------------------------------------------------------------------------

def _thinking_me(question: str, params: dict) -> str:
    return (
        "Entity: current user (me)\n"
        "Operation: get my own profile — no ID needed\n"
        "Endpoint: GET /v1/me\n"
        "Params: {}"
    )


def _thinking_by_id(question: str, entity: str, endpoint: str, params: dict) -> str:
    list_endpoint = re.sub(r"/\{[^}]+\}$", "", endpoint)
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""

    lines = [f"Entity: {entity}"]
    if domain_note:
        lines.append(f"Domain: {domain_note}")
    elif synonym:
        lines.append(f"Synonym: '{synonym}' maps to {entity}")

    if not params:
        lines += [
            "Scope: single item lookup -- ID should be in params",
            f"Use:    {endpoint}",
            f"NOT:    {list_endpoint} (that is the list endpoint)",
        ]
        return "\n".join(lines)

    id_key, id_val = next(iter(params.items()))
    lines += [
        f"Scope: single item -- the prompt contains an explicit ID ({id_val})",
        f"The number {id_val} is the {id_key}, not a page number or filter",
        f"Use:    {endpoint}",
        f"NOT:    {list_endpoint} (that is the list endpoint, requires an ID)",
        f"Params: {json.dumps(params)}",
    ]
    return "\n".join(lines)


def _thinking_list(question: str, entity: str, endpoint: str, params: dict) -> str:
    id_endpoint = endpoint.rstrip("/") + "/{id}"
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""
    is_possession = _possession_no_filter(question)
    is_descriptor = _measurement_descriptor(question)

    lines = [f"Entity: {entity}"]
    if domain_note:
        lines.append(f"Domain: {domain_note}")
    elif synonym:
        lines.append(f"Synonym: '{synonym}' maps to {entity}")

    if not params:
        lines.append("Scope: list all -- no ID present, return the full list")
        if is_possession:
            lines.append(
                f"Possession note: '{question}' uses possessive phrasing but does NOT imply a filter. "
                f"{endpoint} already returns only the authenticated user's data."
            )
        if is_descriptor and entity == "measurements":
            lines.append(
                "No filter: descriptive phrases like 'reach and frequency' or 'campaign performance' "
                "describe the kind of data, not a query parameter. Do not add metric=, type=, or any filter."
            )
        lines += [
            f"Use:    {endpoint}",
            f"NOT:    {id_endpoint} (that requires an explicit numeric ID)",
            "Params: {}",
        ]
    else:
        page_size = params.get("pageSize")
        filters = {k: v for k, v in params.items() if k not in ("pageSize", "pageToken")}
        lines.append("Scope: list")
        if page_size:
            lines.append(f"Requested count: {page_size}")
        if filters:
            lines.append(f"Filters: {', '.join(f'{k}={v}' for k, v in filters.items())}")
        lines += [f"Endpoint: {endpoint}", f"Params: {json.dumps(params)}"]

    return "\n".join(lines)


def _thinking_chained(question: str, steps: list) -> str:
    if len(steps) < 2:
        return "Multi-step operation — see steps for details"

    step0 = steps[0]
    step1 = steps[1]
    entity0, _ = _infer(step0["endpoint"])
    entity1, _ = _infer(step1["endpoint"])

    # Find the template variable reference (e.g. {{steps.0.programId}})
    dep = ""
    for v in step1["params"].values():
        m = re.search(r"\{\{steps\.0\.(\w+)\}\}", str(v))
        if m:
            dep = m.group(1)
            break

    lines = [
        f"Goal: retrieve a specific {entity1} without a known ID",
        f"Step 0: list {entity0} to obtain an ID → {step0['endpoint']}",
        f"Step 1: use {{{{steps.0.{dep}}}}} to fetch the specific {entity1} → {step1['endpoint']}",
        "Two-step chain: the ID is resolved at runtime from step 0's response",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main dispatcher
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Manual thinking traces for edge cases the templates cannot fully handle.
# Keyed by normalized (lowercase, stripped) question text.
# These override deterministic generation for exact matches.
# ---------------------------------------------------------------------------

_MANUAL: dict[str, str] = {

    # --- Measurements: campaign synonyms ---
    "list campaigns": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /campaigns endpoint. The word 'campaigns' here refers to ad "
        "campaign performance data, which lives at /external/v1/measurements.\n"
        "Scope: list all ad measurements (campaigns)\n"
        "Use:    GET /external/v1/measurements\n"
        "NOT:    GET /external/v1/campaigns (that endpoint does not exist in VideoAmp)\n"
        "Params: {}"
    ),
    "my ad campaigns": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /campaigns endpoint. 'My ad campaigns' means 'my ad measurements'.\n"
        "Possession: does NOT imply a filter -- /measurements returns all the authenticated user's data.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "show campaign data": (
        "Entity: measurements\n"
        "Domain: 'Campaign data' is ad measurement data in VideoAmp. There is no /campaigns endpoint.\n"
        "Note: 'show' here means 'display', not a TV show.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "campaign performance": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /performance or /campaigns endpoint. Campaign performance is "
        "tracked as ad measurements at /external/v1/measurements.\n"
        "Descriptor: 'campaign performance' describes what kind of data -- it is not a filter value.\n"
        "Do NOT add performance=, type=, or metric= parameters.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),

    # --- Measurements: report synonyms ---
    "show my reports": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /reports endpoint. 'Reports' in VideoAmp are called measurements.\n"
        "Possession: 'my reports' does NOT filter by owner -- /measurements already returns only "
        "the authenticated user's data.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "NOT:    GET /external/v1/reports (that endpoint does not exist)\n"
        "Params: {}"
    ),
    "show me my report": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /reports endpoint. 'My report' is ad measurement data.\n"
        "Decision: two wrong paths to reject explicitly:\n"
        "  WRONG: GET /external/v1/reports — this endpoint does not exist in VideoAmp\n"
        "  WRONG: GET /external/v1/content/programs — 'report' is not a TV program\n"
        "Possession: 'my' does NOT add a filter. /measurements already scopes to the authenticated user.\n"
        "No ID: no measurement ID was given, so this is a list call not a by-ID call.\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "my reports": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /reports endpoint. 'My reports' = my ad measurements.\n"
        "Possession: does NOT imply a filter.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "my ad reports": (
        "Entity: measurements\n"
        "Domain: 'Ad reports' are ad measurements in VideoAmp.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "what are my ad reports": (
        "Entity: measurements\n"
        "Domain: VideoAmp has no /reports endpoint. 'Ad reports' = ad measurements.\n"
        "Possession: 'my' does NOT add a filter -- /measurements returns the user's own data.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "media performance reports": (
        "Entity: measurements\n"
        "Domain: 'Media performance reports' are ad measurements in VideoAmp.\n"
        "No filter: 'media performance' is a descriptor, not a query parameter.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),

    # --- Measurements: reach/frequency/impressions ---
    "reach and frequency data": (
        "Entity: measurements\n"
        "Domain: Reach and frequency are metrics within VideoAmp ad measurements. "
        "There is no /reach endpoint and no metric= filter on /measurements.\n"
        "Descriptor: 'reach and frequency' describes the kind of data the user wants. "
        "It is NOT a query parameter. Do not add metric=, type=, or any filter.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "reach and frequency": (
        "Entity: measurements\n"
        "Domain: Reach and frequency are metrics within ad measurements, not a separate endpoint.\n"
        "No filter: do not infer metric= or type= parameters.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "my impressions": (
        "Entity: measurements\n"
        "Domain: Impressions are a metric within VideoAmp ad measurements, not a separate endpoint.\n"
        "Possession + descriptor: 'my impressions' means list my ad measurements. No filter implied.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),
    "impression data": (
        "Entity: measurements\n"
        "Domain: Impression data is part of VideoAmp ad measurements. No /impressions endpoint exists.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/measurements\n"
        "Params: {}"
    ),

    # --- Measurements: my measurement (disambiguation from by-ID) ---
    "my measurement": (
        "Entity: measurements\n"
        "Scope: list all -- 'my measurement' uses possessive phrasing with NO numeric ID.\n"
        "Possession: does NOT imply a filter. /measurements returns all the user's data.\n"
        "Disambiguation: without an explicit ID (like 'measurement abc-123'), this is a list call.\n"
        "Use:    GET /external/v1/measurements (list)\n"
        "NOT:    GET /external/v1/measurements/{id} (that requires an explicit ID)\n"
        "No filter: do not add status=, type=, or any inferred parameter.\n"
        "Params: {}"
    ),

    # --- Networks: channel synonyms ---
    "tv channels": (
        "Entity: networks\n"
        "Domain: VideoAmp has no /channels endpoint. TV channels (broadcast networks) are "
        "represented as 'networks' at /external/v1/content/networks.\n"
        "Scope: list all networks\n"
        "Use:    GET /external/v1/content/networks\n"
        "NOT:    GET /external/v1/content/channels (that endpoint does not exist)\n"
        "Params: {}"
    ),
    "what channels exist": (
        "Entity: networks\n"
        "Domain: VideoAmp has no /channels endpoint. Channels are networks.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/content/networks\n"
        "Params: {}"
    ),
    "show channels": (
        "Entity: networks\n"
        "Domain: 'Channels' = VideoAmp networks. No /channels endpoint exists.\n"
        "Note: 'show' means display, not a TV show.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/content/networks\n"
        "Params: {}"
    ),
    "list channels": (
        "Entity: networks\n"
        "Domain: VideoAmp has no /channels endpoint. Channels are networks.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/content/networks\n"
        "Params: {}"
    ),
    "all tv channels": (
        "Entity: networks\n"
        "Domain: TV channels are 'networks' in VideoAmp. No /channels endpoint.\n"
        "Scope: list all\n"
        "Use:    GET /external/v1/content/networks\n"
        "Params: {}"
    ),

    # --- Audiences: segment synonyms ---
    "audience segments": (
        "Entity: audiences\n"
        "Domain: VideoAmp has no /segments endpoint. Audience segments are simply 'audiences' "
        "at /v1/audiences.\n"
        "Scope: list all\n"
        "Use:    GET /v1/audiences\n"
        "NOT:    GET /v1/audiences/segments (that path does not exist)\n"
        "Params: {}"
    ),
    "my segments": (
        "Entity: audiences\n"
        "Domain: 'Segments' = VideoAmp audiences. No /segments endpoint.\n"
        "Possession: does NOT add a filter.\n"
        "Scope: list all\n"
        "Use:    GET /v1/audiences\n"
        "Params: {}"
    ),
    "demographic segments": (
        "Entity: audiences\n"
        "Domain: Demographic segments are audiences in VideoAmp. No /demographics or /segments endpoint.\n"
        "Descriptor: 'demographic' describes the type -- it is not a query filter.\n"
        "Scope: list all\n"
        "Use:    GET /v1/audiences\n"
        "Params: {}"
    ),
    "all segments": (
        "Entity: audiences\n"
        "Domain: 'Segments' = VideoAmp audiences. No /segments endpoint.\n"
        "Scope: list all\n"
        "Use:    GET /v1/audiences\n"
        "Params: {}"
    ),
    "my audience segments": (
        "Entity: audiences\n"
        "Domain: Audience segments are audiences. No /segments endpoint.\n"
        "Possession: does NOT add a filter.\n"
        "Scope: list all\n"
        "Use:    GET /v1/audiences\n"
        "Params: {}"
    ),

    # --- Episodes: emphasize params must be included ---
    "give me episode 33": (
        "Entity: episode\n"
        "Scope: single item -- '33' is the episodeId\n"
        "The number 33 is the resource ID, not a page number\n"
        "IMPORTANT: the episodeId value MUST be included in params\n"
        "Use:    GET /external/v1/content/episodes/{episodeId}\n"
        "NOT:    GET /external/v1/content/episodes (that is the list, no ID)\n"
        "Params: {\"episodeId\": 33}  <-- episodeId is required, do not omit it"
    ),
    "see episode 22": (
        "Entity: episode\n"
        "Scope: single item -- '22' is the episodeId\n"
        "The number 22 is the resource ID, not a page number\n"
        "IMPORTANT: the episodeId value MUST be included in params\n"
        "Use:    GET /external/v1/content/episodes/{episodeId}\n"
        "NOT:    GET /external/v1/content/episodes (that is the list endpoint)\n"
        "Params: {\"episodeId\": 22}  <-- episodeId is required"
    ),
}



# ---------------------------------------------------------------------------
# QOC thinking trace generators (Question / Option / Criteria)
# For larger models and structured decision-matrix reasoning.
# ---------------------------------------------------------------------------

def _qoc_me(question: str, params: dict) -> str:
    return (
        "Question: Which endpoint returns the authenticated user's profile?\n"
        "Option:   GET /v1/me\n"
        "Criteria: No ID required. This endpoint always returns the current user. No alternatives.\n"
        "Params: {}"
    )


def _qoc_by_id(question: str, entity: str, endpoint: str, params: dict) -> str:
    list_endpoint = re.sub(r"/\{[^}]+\}$", "", endpoint)
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""

    lines = [f"Question: Retrieve a single {entity} by ID, or list all {entity}?"]
    if domain_note:
        lines.append(f"Domain:   {domain_note}")

    if not params:
        lines += [
            f"Option A: {endpoint}  (single item by ID)",
            f"Option B: {list_endpoint}  (list endpoint — no ID)",
            "Criteria: ID required for Option A but not provided. Defaulting to single-item intent.",
            f"Use:      {endpoint}",
        ]
        return "\n".join(lines)

    id_key, id_val = next(iter(params.items()))
    lines += [
        f"Option A: {endpoint}  (single item — requires {id_key})",
        f"Option B: {list_endpoint}  (list — no ID needed)",
        f"Criteria: Prompt contains explicit numeric ID '{id_val}'. "
        f"'{id_val}' is the {id_key}, not a page number or filter. Option A wins.",
        f"Params:   {json.dumps(params)}",
    ]
    return "\n".join(lines)


def _qoc_list(question: str, entity: str, endpoint: str, params: dict) -> str:
    id_endpoint = endpoint.rstrip("/") + "/{id}"
    synonym = _detect_synonym(question, entity)
    domain_note = _SYNONYM_DOMAIN_NOTES.get((synonym, entity), "") if synonym else ""
    is_possession = _possession_no_filter(question)
    is_descriptor = _measurement_descriptor(question)

    lines = [f"Question: List all {entity}, or retrieve a single {entity} by ID?"]
    if domain_note:
        lines.append(f"Domain:   {domain_note}")

    if not params:
        lines += [
            f"Option A: {endpoint}  (list — no ID required)",
            f"Option B: {id_endpoint}  (single item — requires explicit numeric ID)",
        ]
        criteria = "No numeric ID in prompt."
        if is_possession:
            criteria += (
                f" Possessive phrasing does not imply an ID — "
                f"{endpoint} already scopes to the authenticated user."
            )
        if is_descriptor and entity == "measurements":
            criteria += (
                " Descriptive phrase does not translate to a filter parameter. "
                "Do not add metric=, type=, currencyOfRecord=, or any inferred filter."
            )
        criteria += " Option A wins."
        lines += [f"Criteria: {criteria}", "Params:   {}"]
    else:
        page_size = params.get("pageSize")
        filters = {k: v for k, v in params.items() if k not in ("pageSize", "pageToken")}
        lines += [
            f"Option A: {endpoint}  (list)",
            f"Option B: {id_endpoint}  (single item — no ID in prompt)",
            f"Criteria: No ID present; list intent confirmed."
            + (f" Count: {page_size}." if page_size else "")
            + (f" Filters: {', '.join(f'{k}={v}' for k,v in filters.items())}." if filters else ""),
            f"Endpoint: {endpoint}",
            f"Params:   {json.dumps(params)}",
        ]
    return "\n".join(lines)


def _qoc_chained(question: str, steps: list) -> str:
    if len(steps) < 2:
        return "Multi-step operation — see steps for details"
    step0, step1 = steps[0], steps[1]
    entity0, _ = _infer(step0["endpoint"])
    entity1, _ = _infer(step1["endpoint"])
    dep = ""
    for v in step1["params"].values():
        m = re.search(r"\{\{steps\.0\.(\w+)\}\}", str(v))
        if m:
            dep = m.group(1); break
    return (
        f"Question: How to retrieve a specific {entity1} when only the name/context is known, not the ID?\n"
        f"Option A: Direct GET {step1['endpoint']} — requires known {dep}\n"
        f"Option B: Two-step — list {entity0} first, resolve ID, then fetch {entity1}\n"
        f"Criteria: ID not supplied in prompt. Option B required.\n"
        f"Step 0:   {step0['endpoint']} — obtain {dep}\n"
        f"Step 1:   {step1['endpoint']} — use {{{{steps.0.{dep}}}}}"
    )


# QOC manual overrides for the hard synonym/disambiguation cases
_MANUAL_QOC: dict[str, str] = {
    "list campaigns": (
        "Question: Which endpoint serves ad campaign data?\n"
        "Option A: GET /external/v1/measurements  (VideoAmp ad measurements)\n"
        "Option B: GET /external/v1/campaigns  (does not exist)\n"
        "Criteria: VideoAmp has no /campaigns endpoint. 'Campaigns' = ad measurements. Option B is invalid. Option A wins.\n"
        "Params:   {}"
    ),
    "show me my report": (
        "Question: Which endpoint serves 'my report' data?\n"
        "Option A: GET /external/v1/measurements  (ad measurement results)\n"
        "Option B: GET /external/v1/reports  (does not exist)\n"
        "Option C: GET /external/v1/content/programs  (TV programs — unrelated)\n"
        "Criteria: VideoAmp has no /reports endpoint. 'Report' = measurement. No ID provided, so this is a list. Options B and C are invalid. Option A wins.\n"
        "Params:   {}"
    ),
    "show my reports": (
        "Question: Which endpoint serves 'my reports' data?\n"
        "Option A: GET /external/v1/measurements\n"
        "Option B: GET /external/v1/reports  (does not exist)\n"
        "Criteria: 'Reports' = measurements. /reports does not exist. Possession does not add a filter. Option A wins.\n"
        "Params:   {}"
    ),
    "reach and frequency data": (
        "Question: Which endpoint serves reach and frequency data?\n"
        "Option A: GET /external/v1/measurements  (ad measurements including R&F metrics)\n"
        "Option B: GET /external/v1/measurements with metric= filter  (invalid — no metric param)\n"
        "Criteria: Reach and frequency are metrics within measurements, not filter values or a separate endpoint. No filter should be added. Option A wins.\n"
        "Params:   {}"
    ),
    "campaign performance": (
        "Question: Which endpoint serves campaign performance data?\n"
        "Option A: GET /external/v1/measurements\n"
        "Option B: GET /external/v1/campaigns  (does not exist)\n"
        "Criteria: VideoAmp has no /campaigns or /performance endpoint. Campaign performance = ad measurements. No filter implied. Option A wins.\n"
        "Params:   {}"
    ),
    "my impressions": (
        "Question: Which endpoint serves impression data?\n"
        "Option A: GET /external/v1/measurements\n"
        "Option B: GET /external/v1/impressions  (does not exist)\n"
        "Criteria: Impressions are a metric within ad measurements. No /impressions endpoint exists. Possession does not add a filter. Option A wins.\n"
        "Params:   {}"
    ),
    "tv channels": (
        "Question: Which endpoint lists TV channels?\n"
        "Option A: GET /external/v1/content/networks\n"
        "Option B: GET /external/v1/content/channels  (does not exist)\n"
        "Criteria: VideoAmp calls TV channels 'networks'. /channels does not exist. Option A wins.\n"
        "Params:   {}"
    ),
    "channel 45": (
        "Question: Retrieve a single channel (network) by ID, or list all?\n"
        "Option A: GET /external/v1/content/networks/{id}  (single network by ID)\n"
        "Option B: GET /external/v1/content/channels/{id}  (does not exist)\n"
        "Criteria: 'Channel' = VideoAmp network. '45' is the network ID. /channels does not exist. Option A wins.\n"
        "Params:   {\"id\": 45}"
    ),
    "audience segments": (
        "Question: Which endpoint lists audience segments?\n"
        "Option A: GET /v1/audiences\n"
        "Option B: GET /v1/audiences/segments  (does not exist)\n"
        "Criteria: VideoAmp calls audience segments simply 'audiences'. /audiences/segments does not exist. Option A wins.\n"
        "Params:   {}"
    ),
    "my segments": (
        "Question: Which endpoint lists 'my segments'?\n"
        "Option A: GET /v1/audiences\n"
        "Option B: GET /v1/segments  (does not exist)\n"
        "Criteria: 'Segments' = audiences. /segments does not exist. Possession does not add a filter. Option A wins.\n"
        "Params:   {}"
    ),
    "demographic segments": (
        "Question: Which endpoint serves demographic segments?\n"
        "Option A: GET /v1/audiences\n"
        "Option B: GET /v1/demographics  (does not exist)\n"
        "Criteria: Demographic segments are audiences. /demographics and /segments do not exist. 'Demographic' is a descriptor, not a filter. Option A wins.\n"
        "Params:   {}"
    ),
    "my measurement": (
        "Question: List all measurements, or retrieve a single measurement by ID?\n"
        "Option A: GET /external/v1/measurements  (list)\n"
        "Option B: GET /external/v1/measurements/{id}  (single item — requires UUID)\n"
        "Criteria: No ID provided. Possessive 'my' does not supply an ID. /measurements already scopes to the authenticated user. Do not add status=, type=, or any inferred filter. Option A wins.\n"
        "Params:   {}"
    ),
    "audiences": (
        "Question: List all audiences, or retrieve a single audience by ID?\n"
        "Option A: GET /v1/audiences  (list)\n"
        "Option B: GET /v1/audiences/{id}  (single item — requires numeric ID)\n"
        "Criteria: Bare noun with no ID. Option A wins.\n"
        "Params:   {}"
    ),
}


def generate_thinking(question: str, api_call: dict, style: str = "linear") -> str:
    """Return a thinking trace string for a training record.
    style: 'linear' (default, Entity/Scope/Use/NOT) or 'qoc' (Question/Option/Criteria).
    """
    normalized = question.strip().lower()

    if style == "qoc":
        if normalized in _MANUAL_QOC:
            return _MANUAL_QOC[normalized]
        if "steps" in api_call:
            return _qoc_chained(question, api_call["steps"])
        endpoint = api_call.get("endpoint", "")
        params = api_call.get("params", {})
        if re.search(r"/v1/me$", endpoint):
            return _qoc_me(question, params)
        entity, is_by_id = _infer(endpoint)
        return _qoc_by_id(question, entity, endpoint, params) if is_by_id else _qoc_list(question, entity, endpoint, params)

    # --- linear (default) ---
    if normalized in _MANUAL:
        return _MANUAL[normalized]

    if "steps" in api_call:
        return _thinking_chained(question, api_call["steps"])

    endpoint = api_call.get("endpoint", "")
    params = api_call.get("params", {})

    # /v1/me special case
    if re.search(r"/v1/me$", endpoint):
        return _thinking_me(question, params)

    entity, is_by_id = _infer(endpoint)
    if is_by_id:
        return _thinking_by_id(question, entity, endpoint, params)
    else:
        return _thinking_list(question, entity, endpoint, params)


# ---------------------------------------------------------------------------
# File processing
# ---------------------------------------------------------------------------

def enrich_file(path: Path, dry_run: bool = False, sample: int = 0, force: bool = False, style: str = "linear") -> int:
    """Read, enrich, and rewrite a training.jsonl file. Returns record count."""
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            if force or "thinking" not in rec:
                rec["thinking"] = generate_thinking(
                    rec["question"], rec["api_call"], style=style
                )
            records.append(rec)

    if sample > 0:
        for rec in records[:sample]:
            print(f"\nQ: {rec['question']!r}")
            print(f"Thinking:\n{rec['thinking']}")
            print(f"Answer: {json.dumps(rec['api_call'])[:80]}")
        return len(records)

    if not dry_run:
        with open(path, "w") as f:
            for rec in records:
                f.write(json.dumps(rec) + "\n")

    return len(records)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input-dir", required=True,
                        help="Directory containing endpoint subdirs with training.jsonl")
    parser.add_argument("--endpoint", default=None,
                        help="Process only this endpoint subdirectory")
    parser.add_argument("--trace-style", choices=["linear", "qoc"], default="linear",
                        help="Thinking trace format: 'linear' (Entity/Scope/Use) or 'qoc' (Question/Option/Criteria)")
    parser.add_argument("--force", action="store_true",
                        help="Re-generate thinking for records that already have it")
    parser.add_argument("--dry-run", action="store_true",
                        help="Do not write files — print counts only")
    parser.add_argument("--sample", type=int, default=0,
                        help="Print N sample thinking traces instead of writing")
    args = parser.parse_args()

    input_dir = Path(args.input_dir).expanduser()
    if not input_dir.is_dir():
        sys.exit(f"Not a directory: {input_dir}")

    if args.endpoint:
        files = [input_dir / args.endpoint / "training.jsonl"]
    else:
        files = sorted(input_dir.glob("*/training.jsonl"))

    if not files:
        sys.exit(f"No training.jsonl files found under {input_dir}")

    total = 0
    for path in files:
        if not path.exists():
            print(f"  SKIP  {path} (not found)")
            continue
        count = enrich_file(path, dry_run=args.dry_run, sample=args.sample, force=args.force, style=args.trace_style)
        action = "would write" if args.dry_run else "wrote"
        print(f"  {action}  {count:4d} records  {path.parent.name}")
        total += count

    print(f"\n  Total: {total} records across {len(files)} endpoint(s)")
    if args.dry_run:
        print("  (dry run — no files modified)")


if __name__ == "__main__":
    main()
