#!/usr/bin/env python3
"""
Add structured thinking traces to existing apisynth training records.

Reads data/videoamp/*/training.jsonl records and writes them back with a
"thinking" field inserted between "question" and "api_call". The trace is
derived deterministically from the api_call — no teacher LLM required for
simple single-endpoint records.

For complex multi-step records (future PoC workflows), the thinking field
should be generated by a teacher LLM and passed in as an override file.

Usage:
    # Enrich all endpoints in-place (adds "thinking" to existing records):
    python scripts/add_thinking.py --input-dir data/videoamp

    # Dry-run: print sample thinking traces without writing:
    python scripts/add_thinking.py --input-dir data/videoamp --dry-run --sample 5

    # Enrich a single endpoint:
    python scripts/add_thinking.py --input-dir data/videoamp --endpoint programs
"""

import argparse
import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Entity and operation inference from endpoint strings
# ---------------------------------------------------------------------------

# Map endpoint path patterns to human-readable entity names
_EP_ENTITY = [
    (r"/content/programs/\{",        "program",      True),
    (r"/content/programs$",          "programs",     False),
    (r"/content/episodes/\{",        "episode",      True),
    (r"/content/episodes$",          "episodes",     False),
    (r"/content/networks/\{",        "network",      True),
    (r"/content/networks$",          "networks",     False),
    (r"/content/media-groups$",      "media groups", False),
    (r"/content/metric-type",        "metric types", False),
    (r"/content/metrics/\{",         "content metric", True),
    (r"/measurements/\{",            "measurement",  True),
    (r"/measurements$",              "measurements", False),
    (r"/audiences/status$",          "audience statuses", False),
    (r"/audiences/\{[^}]+\}/exports",  "audience exports", False),
    (r"/audiences/\{",               "audience",     True),
    (r"/audiences$",                 "audiences",    False),
    (r"/currency-of-record",         "currency of record", False),
    (r"/consents$",                  "consents",     False),
    (r"/v1/me$",                     "me",           False),
]

def _infer(endpoint: str):
    """Return (entity_name, is_by_id) for an endpoint string."""
    for pattern, name, by_id in _EP_ENTITY:
        if re.search(pattern, endpoint):
            return name, by_id
    # Fallback: extract last path segment
    parts = endpoint.rstrip("/").split("/")
    last = parts[-1] if parts else "resource"
    is_by_id = last.startswith("{")
    if is_by_id:
        entity = parts[-2] if len(parts) > 1 else "resource"
    else:
        entity = last.replace("-", " ")
    return entity, is_by_id


# ---------------------------------------------------------------------------
# Thinking trace generators
# ---------------------------------------------------------------------------

def _thinking_me(question: str, params: dict) -> str:
    return (
        "Entity: current user (me)\n"
        "Operation: get my own profile — no ID needed\n"
        "Endpoint: GET /v1/me\n"
        "Params: {}"
    )


def _thinking_by_id(question: str, entity: str, endpoint: str, params: dict) -> str:
    if not params:
        return (
            f"Entity: {entity}\n"
            f"Operation: single-item lookup — ID should be in params\n"
            f"Endpoint: {endpoint}\n"
            f"Params: {{}}"
        )
    id_key, id_val = next(iter(params.items()))
    lines = [
        f"Entity: {entity}",
        f"Operation: single-item lookup by {id_key}",
        f"ID: {id_key} = {id_val}",
        f"The prompt refers to a specific {entity}, not a list",
        f"Endpoint: {endpoint}",
        f"Params: {json.dumps(params)}",
    ]
    return "\n".join(lines)


def _thinking_list(question: str, entity: str, endpoint: str, params: dict) -> str:
    if not params:
        lines = [
            f"Entity: {entity}",
            "Operation: list all — no filters or page size requested",
            f"Endpoint: {endpoint}",
            "Params: {}",
        ]
    else:
        # Separate pageSize from filters
        page_size = params.get("pageSize")
        filters = {k: v for k, v in params.items() if k not in ("pageSize", "pageToken")}

        lines = [f"Entity: {entity}", "Operation: list"]
        if page_size:
            lines.append(f"Requested count: {page_size}")
        if filters:
            filter_desc = ", ".join(f"{k}={v}" for k, v in filters.items())
            lines.append(f"Filters: {filter_desc}")
        lines.append(f"Endpoint: {endpoint}")
        lines.append(f"Params: {json.dumps(params)}")

    return "\n".join(lines)


def _thinking_chained(question: str, steps: list) -> str:
    if len(steps) < 2:
        return "Multi-step operation — see steps for details"

    step0 = steps[0]
    step1 = steps[1]
    entity0, _ = _infer(step0["endpoint"])
    entity1, _ = _infer(step1["endpoint"])

    # Find the template variable reference (e.g. {{steps.0.programId}})
    dep = ""
    for v in step1["params"].values():
        m = re.search(r"\{\{steps\.0\.(\w+)\}\}", str(v))
        if m:
            dep = m.group(1)
            break

    lines = [
        f"Goal: retrieve a specific {entity1} without a known ID",
        f"Step 0: list {entity0} to obtain an ID → {step0['endpoint']}",
        f"Step 1: use {{{{steps.0.{dep}}}}} to fetch the specific {entity1} → {step1['endpoint']}",
        "Two-step chain: the ID is resolved at runtime from step 0's response",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main dispatcher
# ---------------------------------------------------------------------------

def generate_thinking(question: str, api_call: dict) -> str:
    """Return a thinking trace string for a training record."""
    if "steps" in api_call:
        return _thinking_chained(question, api_call["steps"])

    endpoint = api_call.get("endpoint", "")
    params = api_call.get("params", {})

    # /v1/me special case
    if re.search(r"/v1/me$", endpoint):
        return _thinking_me(question, params)

    entity, is_by_id = _infer(endpoint)
    if is_by_id:
        return _thinking_by_id(question, entity, endpoint, params)
    else:
        return _thinking_list(question, entity, endpoint, params)


# ---------------------------------------------------------------------------
# File processing
# ---------------------------------------------------------------------------

def enrich_file(path: Path, dry_run: bool = False, sample: int = 0) -> int:
    """Read, enrich, and rewrite a training.jsonl file. Returns record count."""
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            if "thinking" not in rec:
                rec["thinking"] = generate_thinking(
                    rec["question"], rec["api_call"]
                )
            records.append(rec)

    if sample > 0:
        for rec in records[:sample]:
            print(f"\nQ: {rec['question']!r}")
            print(f"Thinking:\n{rec['thinking']}")
            print(f"Answer: {json.dumps(rec['api_call'])[:80]}")
        return len(records)

    if not dry_run:
        with open(path, "w") as f:
            for rec in records:
                f.write(json.dumps(rec) + "\n")

    return len(records)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input-dir", required=True,
                        help="Directory containing endpoint subdirs with training.jsonl")
    parser.add_argument("--endpoint", default=None,
                        help="Process only this endpoint subdirectory")
    parser.add_argument("--dry-run", action="store_true",
                        help="Do not write files — print counts only")
    parser.add_argument("--sample", type=int, default=0,
                        help="Print N sample thinking traces instead of writing")
    args = parser.parse_args()

    input_dir = Path(args.input_dir).expanduser()
    if not input_dir.is_dir():
        sys.exit(f"Not a directory: {input_dir}")

    if args.endpoint:
        files = [input_dir / args.endpoint / "training.jsonl"]
    else:
        files = sorted(input_dir.glob("*/training.jsonl"))

    if not files:
        sys.exit(f"No training.jsonl files found under {input_dir}")

    total = 0
    for path in files:
        if not path.exists():
            print(f"  SKIP  {path} (not found)")
            continue
        count = enrich_file(path, dry_run=args.dry_run, sample=args.sample)
        action = "would write" if args.dry_run else "wrote"
        print(f"  {action}  {count:4d} records  {path.parent.name}")
        total += count

    print(f"\n  Total: {total} records across {len(files)} endpoint(s)")
    if args.dry_run:
        print("  (dry run — no files modified)")


if __name__ == "__main__":
    main()
